management.endpoints.web.base-path: /actuator
#перечисляем доступные точки
management.endpoints.web.exposure.include: info,beans,metrics,health,shutdown
#порт основного приложения
server:
  port: 8888

# порт для актуатора
management.server.port: 8889


#оиг пароль для актуатора
spring:
  security:
    user:
      name: login
      password: password

